using System;
using System.Windows.Forms;
using System.Collections.Generic;
using DevExpress.LookAndFeel;
using DevExpress.XtraGrid.Views.Grid;
using TheepClass;

namespace MPS02
{
    public partial class MPS02 : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        List<DocumentStatus> documentStatuses;
        public MPS02()
        {
            InitializeComponent();
            UserLookAndFeel.Default.StyleChanged += MyStyleChanged;
            documentStatuses = new List<DocumentStatus>();
            documentStatuses.Add(new DocumentStatus { ID = 0, Status = "New" });
            documentStatuses.Add(new DocumentStatus { ID = 1, Status = "Revise" });
            documentStatuses.Add(new DocumentStatus { ID = 2, Status = "Change" });
            documentStatuses.Add(new DocumentStatus { ID = 3, Status = "Cancel" });
            documentStatuses.Add(new DocumentStatus { ID = 9, Status = "Finished" });
        }

        private void MyStyleChanged(object sender, EventArgs e)
        {
            UserLookAndFeel userLookAndFeel = (UserLookAndFeel)sender;
            cUtility.SaveRegistry(@"Software\MDS", "SkinName", userLookAndFeel.SkinName);
            cUtility.SaveRegistry(@"Software\MDS", "SkinPalette", userLookAndFeel.ActiveSvgPaletteName);
        }

        private void XtraForm1_Load(object sender, EventArgs e)
        {
            gridLookUpEdit5.Properties.DataSource = documentStatuses;
            gridLookUpEdit5.Properties.DisplayMember = "Status";
            gridLookUpEdit5.Properties.ValueMember = "ID";
            gridLookUpEdit6.Properties.DataSource = documentStatuses;
            gridLookUpEdit6.Properties.DisplayMember = "Status";
            gridLookUpEdit6.Properties.ValueMember = "ID";
        }

        private void bbiNew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void bbiSave_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void bbiExcel_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
        }

        private void bbiPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void bbiPrint_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValueNeeded(object sender, DevExpress.Data.UnboundSourceValueNeededEventArgs e)
        {
            // Handle this event to obtain data from your data source
            // e.Value = something /* TODO: Assign the real data here.*/
        }

        // This event is generated by Data Source Configuration Wizard
        void unboundSource1_ValuePushed(object sender, DevExpress.Data.UnboundSourceValuePushedEventArgs e)
        {
            // Handle this event to save modified data back to your data source
            // something = e.Value; /* TODO: Propagate the value into the storage.*/
        }
    }

    public class DocumentStatus
    { 
        public int ID { get; set; }
        public string Status { get; set; }
    }
}